### ISSUE TITLE
Port to LiveScript or ES6?

### ISSUE THREAD

**Issue by tomek-he-him** [DanielHoffmann/jquery-svg-pan-zoom#11]
I've had a go at developing `svgPanZoom` in CoffeeScript. It's definitely fun.

But there's one thing which bothers me a lot – implicit scoping. It can lead to unexpected bugs – hard to find as well. Here's a good contrived example: http://raganwald.com/2013/07/27/Ive-always-been-mad.html.

I suggest one of two things.
- **Port to [LiveScript](http://livescript.net/)**

It's very similar to CoffeeScript, so porting shouldn't be much work. I don't have any experience with LS though.
- **Port to [ES6](https://robots.thoughtbot.com/replace-coffeescript-with-es6) using [babel (formerly 6to5)](https://babeljs.io/)**

ES6 without a build step is the near future anyway. As Blake Williams states in the article I referenced above, ES6 “solves a lot of the problems that CoffeeScript is trying to solve without drastic syntax changes”. IMO that's the way to go.

I've also used babel in numerous projects and it's definitely a great experience!

**Comment by DanielHoffmann** [comment]
Yes the implicit scoping is rather annoying, but you get used to it. It also incentives you to not nest too many callbacks and to name your variables with distinct names. Another coffeescript caveat is the [implicit return](http://programmaticallyspeaking.com/why-i-hate-implicit-return-in-coffeescript.html) statements which can create big performance hits, but implicit returns are actually rather nice if you program in a more functional manner.

Having said that I have no plans to port to LiveScript (you are of course free to fork my plugin), I have more experience with coffeescript and little desire to learn yet another language that compiles down to javascript

**Comment by tomek-he-him** [comment]
@DanielHoffmann absolutely. ES6 is my favorite too. I would be glad to develop in ES6 when we get back to this topic.

Especially since it's very likely for node or io.js to support all of ES6 syntax natively at that time.

**Comment by DanielHoffmann** [comment]
For now I see absolutely no benefits in using ES6, yes it brings a bunch of stuff that CoffeeScript also brought but it still does not bring everything and you still need a transcompiler to be able to use it today.

Until a time comes that I can safely use ES6 without any transcompilers and still reach >95% of the internet browsers I see no benefit compared to CoffeeScript. Even so I would use it only for self-contained open source projects like this one, in my own projects I would still use CoffeeScript because its functional style.
