### ISSUE TITLE
Would be nice: Remove dependency on jQuery?

### ISSUE THREAD

**Issue by tomek-he-him** [DanielHoffmann/jquery-svg-pan-zoom#2]
Hi, and thanks for this elegant piece of code.

Have you considered removing dependency on jQuery? Here's some argumentation http://youmightnotneedjquery.com/ – no need to retype that here :) In my case, I'd be delighted to use your library in a no-jQuery project.

As far as I see, there really wouldn't be much to change. Apart from a couple of `$.extend` calls you seem to use:
- [`$.fn.animate` here and there](https://github.com/DanielHoffmann/jquery-svg-pan-zoom/blob/c313/src/jquery.svg.pan.zoom.coffee#L366) – looking at your implementation, perhaps this could also be hacked out with native CSS transforms – by hooking up to the transformed values with `requestAnimationFrame`? If not, that should be quite easy to implement on our own – since they are linear transforms.
- [`$.fn.css` one or two times](https://github.com/DanielHoffmann/jquery-svg-pan-zoom/blob/c313/src/jquery.svg.pan.zoom.coffee#L502) – `Element.prorotype.getComputedStyle` is not the nicest thing to work with, but it's good enough. JQuery uses the same thing under the hood, doesn't it?

Apart from these – since you seem to use the native DOM quite a lot – it shouldn't be much of a problem to port.

I'd be glad to help if you give the green light :)

Cheers! :boat:

**Comment by tomek-he-him** [comment]
Oh, and we'd want to keep it available as a jQuery plugin, it's still doable:

``` js
if (window.jQuery && window.jQuery.fn) {
  jQuery.fn.svgPanZoom = (options) => /* our bindings */
  }
```

**Comment by DanielHoffmann** [comment]
Hey nice to know someone is interested in my plugin.

I considered not depending on jQuery, but what drove me to use it were the animations, I am not experienced with CSS transforms and I was not sure I could do the same hack I did with jQuery animate to animate the viewBox attribute. I guess if I removed the .animate call I would roll my own javascript animate function (that hack is so ugly it hurts, using CSS transforms the code would still be ugly).

Just a little sidenote the mousewheel event is currently broken in IE and Firefox, there is a pullrequest that fixes it but I did not have time to clean up and test it, next week I will have enough time.to do that. Originally this plugin also depended on (jQuery Mousewheel)[https://github.com/jquery/jquery-mousewheel] but when I removed that dependency the code broke.

These days I have not had much time so I can't remove the dependencies and risk introducing bugs, for my own personal use I need to keep this plugin compatible with IE9 If you feel inclined to implement on your own and can keep it compatible I would gladly merge your changes. If you can not keep it compatible you also have my blessing to fork my project into your own.

**Comment by tomek-he-him** [comment]
To be honest, I have a prototype project targeting only the latest version of Chrome – so comfortable for me :) But fine, I'll take a stab at this.

I was thinking to use this at first: https://github.com/web-animations/web-animations-js. But since we only use linear animations, this would really be overkill. And we'd have to use some hacks, too. So I'm leaning towards implementing animations myself.

**Comment by DanielHoffmann** [comment]
I am closing this issue, rolling my own animation code is too much NIH and besides that this plugin also uses a lot of other jQuery functionality like jQuery.extend(). Sure I could add other dependencies into the library like underscore and web-animations-js but that would be even worse in my opinion, instead of relying on jQuery which most websites use anyway this plugin would either depend on more libraries or inlining said libraries in the plugin itself.

In my opinion you are greatly underestimating the work required to roll your own JS animations, even linear animations require some very precise timing (basically a bunch of setTimeout and currentTime comparisons) and that kind of code is rather annoying to debug.

I do am making some serious effort to keep it compatible with jQuery 1.7 and higher (for example newer jQuery versions have "native" mousewheel functionality). Many websites are stuck on that version.
